### ISSUE TITLE
Typo?: `Ccreator`

### ISSUE THREAD

**Issue by markandrus** [izgzhen/language-webidl-hs#7]
Hi,

First of all, nice package! However, I noticed [here](https://github.com/izgzhen/language-webidl-hs/blob/master/src/Language/WebIDL/AST.hs#L114) it looks like there is a typo (`Ccreator` instead of `Creator`). Should this be `Creator`?

Thanks!
Mark

**Comment by izgzhen** [comment]
Thanks a lot for the feedback and glad that this package might be of use to you.

I checked out https://www.w3.org/TR/WebIDL-1/#prod-Special and the conclusion is that `Ccreator` might be useless at all -- I can't exactly remember how it got introduced, though.

What do you think about it?

**Comment by markandrus** [comment]
Yeah, I think it can be removed. I'm reminded that exception support can be removed and array support, too. See [here](https://github.com/w3c/webidl2.js/pull/67).

**Comment by izgzhen** [comment]
I see. It looks like a lot of things have changed since then. I will revise the new WebIDL spec and try to give a complete set of patch, thanks!

**Comment by izgzhen** [comment]
I've pushed a patch and opened a new issue #8. Let's close this one since the specific problem has been resolved. Thanks again!
